### PR TITLE
fixed removed selectors by referencing the numbered selectors directly

### PR DESCRIPTION
**Pull request by jfoerste**
I had to reference the numbered the numbered selectors directily as I was not able to reference the correct button classes via kss. This might pose a future problem.

### CODE REVIEW

**Comment by KyzaGitHub** [comment]
You are able to get KSS selectors in the console like this.
`KSSMain.findSelectors("buttons-3JBrkn")`

**Comment by jfoerste** [comment]
That serves no purpose as I you could just write ".buttons-3JBrkn" out as a string with the same result. KSS brings an advantage when you can use the |...| notation to find number-independent selectors.

**Comment by KyzaGitHub** [comment]
It serves the purpose to at the very least break much less often. The new KSS version I am working on will hopefully be even more reliable.

**Comment by jfoerste** [comment]
Now everything is in kss notation although it is redundant in line 415.

**Comment by KyzaGitHub** [comment]
That's the wrong plugin. 👌

**Comment by jfoerste** [comment]
Why would you replace the plugins?

**Comment by KyzaGitHub** [comment]
Mistake.

**Pull request merged**
