### PR TITLE
Version number in DarkDark v2's meta

### PR DESCRIPTION
**Pull request by underscore11-wh**

### CODE REVIEW

**Comment by underscore11-wh** [comment]
Wouldn't affect existing users, but new people downloading this would get it.

**Comment by KyzaGitHub** [comment]
Does the version number not show up when the theme is enabled?

**Comment by underscore11-wh** [comment]
Oh I hadn't realized it showed up when the theme was enabled. This way it also says it when it is enabled/disabled however

image

**Comment by KyzaGitHub** [comment]
Since I am depreciating DarkDarkTheme as a theme file, I won't be accepting any PRs for it. They won't be needed since the DDT plugin will be out of beta soon.

**Pull request closed without merging**
